spring:
  application:
    name: e-commerce
  datasource:
    name: ecomm
    url: jdbc:h2:mem:ecomm
    driverClassName: org.h2.Driver
    username: sa
    password:
    DB_CLOSE_DELAY: 1
    IGNORECASE: TRUE
    DATABASE_TO_UPPER: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:ecomm
    user: sa
    password:


#    springdoc:
#      swagger-ui:
#        path: /swagger-ui.html
