spring:
  application:
    name: e-commerce
  datasource:
    name: ecomm
    url: jdbc:h2:mem:ecomm;DATABASE_TO_UPPER=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    DB_CLOSE_DELAY: -1
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ecomm
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

datasource-proxy:
  enabled: true
  logging: slf4j
  multiline: true
  query:
    enable-logging: true
    multiline: true     # TRACE, DEBUG, INFO
    log-level: DEBUG
#    logger-name: datasource-proxy-query   # 원하는 로거명 지정
  slow-query:
#    enable-logging: true
    threshold: 500   # ms 기준 (500ms 초과시 slow query 로깅)
    log-level: WARN
    logger-name: datasource-proxy-slow

#logging:
#  level:
#    datasource-proxy-query: DEBUG
#    datasource-proxy-slow: WARN

logging:
  level:
    net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: DEBUG


#    springdoc:
#      swagger-ui:
#        path: /swagger-ui.html
